name=Ghydra
description=Ghidra HATEOAS interface for all CodeBrowser instances in parallel.
author=Teal Bauer (based on ghidra-mcp by Laurie Wired)
createdOn=2025-03-29
version=11.4.2
ghidraVersion=11.4.2
