name=Ghydra
description=Ghidra HATEOAS interface for all CodeBrowser instances in parallel.
author=Teal Bauer (based on ghidra-mcp by Laurie Wired)
createdOn=2025-03-29
version=3.0.0-rc.1
ghidraVersion=${ghidra.version}
